### PR TITLE
Greyed out controls with AVPlayer - fixes #503

### LINKED ISSUE #503: Greyed out controls with AVPlayer
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When using AVPlayer controls are greyed out, with MPV they work correctly.

IMG_03AD6C88775C-1

### Expected Behavior

To not be greyed out.

### Device & OS Version

iOS 16.5

### App Build

155

### App Settings

_No response_

### Crash log

_No response_

### Screenshots, Videos and other files

_No response_

### PR DESCRIPTION
**Pull request by stonerl**

### CODE REVIEW

**Comment by arekf** [comment]
Unfortunately this does not seem to resolve this for me, is this fixing any specific case of this issue?

**Comment by stonerl** [comment]
Interesting, I had the same problem as the creator of the issue. With the changes, made in the PR, I have working controls on the lock screen now.

IMG_1376
IMG_1375

**Comment by arekf** [comment]
I can reproduce the problem by hiding the player with swipe down. It stays playing with the background but controls are not working anymore. I tried to debug this few times before but did not manage to find the cause yet.

https://github.com/yattee/yattee/assets/367484/45e2734f-f55c-44c3-9d6a-6ef3e5454eef

**Comment by stonerl** [comment]
Which iOS version you're on? I'm running 17.2. Maybe Apple fixed something?

**Comment by arekf** [comment]
Yes, 17.2

**Comment by stonerl** [comment]
Have you tested this on iPhone as well?

I got an iPad today and there the error persists. But on iPhone I cannot recreate it.

**Comment by stonerl** [comment]
Okay, I know now what the issue is, but haven't found a solution — yet. This only happens when the option `Use system controls with AVPlayer` is turned on.

**Pull request closed without merging**
