### PR TITLE
refreshed icons for iOS and macOS

### LINKED ISSUE #700: Add support for iOS 18 tinted icons
This is for later this year on the roadmap : 

More info's here : https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS

image

### PR DESCRIPTION
**Pull request by stonerl**
- added support for adaptive/tinted Icons on iOS.
- closes #700
- new macOS icon set, courtesy of @Kongolabongo (Discourse)

### CODE REVIEW

**Comment by stonerl** [comment]
### iOS Light
Light
### iOS Dark
Dark
### iOS Tinted
Tinted
### macOS
Yattee

**Comment by stonerl** [comment]
That's how it would look like on iOS 18.
### Light
IMG_0072
### Dark
IMG_0073
### Tinted
IMG_0074

**Comment by user858753257** [comment]
@stonerl  many thanks . But how can I activate one of them in the settings ?

**Comment by stonerl** [comment]
@user858753257 we had to revert these. Because we cannot get the app uploaded to testflight right now, with these new icons. If we find a solution we will add them again.

**Comment by user858753257** [comment]
> @user858753257 we had to revert these. Because we cannot get the app uploaded to testflight right now, with these new icons. If we find a solution we will add them again.

Oh ok 🥲

Or we wait approx 2 weeks 🤷

But strange from Apple

**Pull request merged**
